services:
  - type: web
    name: chat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn Chatter.wsgi:application
    staticPublishPath: staticfiles
