# Generated by Django 5.1.3 on 2025-03-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
