# Generated by Django 5.1.3 on 2025-05-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_voice_message_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
    ]
