# Generated by Django 5.1.3 on 2025-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupmessage_voice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
